import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import fs from 'fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2022',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
  jsx: 'automatic',
  plugins: [
    {
      name: 'combine-css',
      setup(build) {
        build.onEnd(() => {
          let customCss = '';
          if (fs.existsSync('src/styles.css')) {
            customCss = fs.readFileSync('src/styles.css', 'utf-8');
          }
          let reactFlowCss = '';
          if (fs.existsSync('main.css')) {
            reactFlowCss = fs.readFileSync('main.css', 'utf-8');
            fs.unlinkSync('main.css');
          }
          fs.writeFileSync('styles.css', reactFlowCss + '\n\n' + customCss);
        });
      },
    },
  ],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
